config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :patients

  resources :orders

  resources :practices

  resources :providers

  resources :ordered_tests

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/ordered_test.rb
class OrderedTest < ActiveRecord::Base
  belongs_to :patient
end

app/controllers/ordered_tests_controller.rb
class OrderedTestsController < ApplicationController
  before_action :set_ordered_test, only: [:show, :edit, :update, :destroy]

  # GET /ordered_tests
  # GET /ordered_tests.json
  def index
    @ordered_tests = OrderedTest.all
  end

  # GET /ordered_tests/1
  # GET /ordered_tests/1.json
  def show
  end

  # GET /ordered_tests/new
  def new
    @ordered_test = OrderedTest.new
  end

  # GET /ordered_tests/1/edit
  def edit
  end

  # POST /ordered_tests
  # POST /ordered_tests.json
  def create
    @ordered_test = OrderedTest.new(ordered_test_params)

    respond_to do |format|
      if @ordered_test.save
        format.html { redirect_to @ordered_test, notice: 'Ordered test was successfully created.' }
        format.json { render :show, status: :created, location: @ordered_test }
      else
        format.html { render :new }
        format.json { render json: @ordered_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordered_tests/1
  # PATCH/PUT /ordered_tests/1.json
  def update
    respond_to do |format|
      if @ordered_test.update(ordered_test_params)
        format.html { redirect_to @ordered_test, notice: 'Ordered test was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordered_test }
      else
        format.html { render :edit }
        format.json { render json: @ordered_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordered_tests/1
  # DELETE /ordered_tests/1.json
  def destroy
    @ordered_test.destroy
    respond_to do |format|
      format.html { redirect_to ordered_tests_url, notice: 'Ordered test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordered_test
      @ordered_test = OrderedTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordered_test_params
      params.require(:ordered_test).permit(:patient_id)
    end
end

app/helpers/ordered_tests_helper.rb
module OrderedTestsHelper
end

app/views/ordered_tests/_form.html.erb
<%= form_for @ordered_test, :html => { :class => 'form-horizontal form-model' } do |f| %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ordered_tests_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ordered_tests/edit.html.erb
<%- model_class = OrderedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => OrderedTest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ordered_tests/index.html.erb
<%- model_class = OrderedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => OrderedTest %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ordered_tests.each do |ordered_test| %>
      <tr>
        <td><%= ordered_test.id %></td>
        <td><%=l ordered_test.created_at, format: :long %></td>
        <td>
          <%= link_to ordered_test_path(ordered_test), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to ordered_test_path(ordered_test), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ordered_test_path,
            :class => 'btn btn-primary' %>

app/views/ordered_tests/new.html.erb
<%- model_class = OrderedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => OrderedTest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ordered_tests/show.html.erb
<%- model_class = OrderedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => OrderedTest %></h1>
</div>

<div class="fieldset">
  <dl>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ordered_tests_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ordered_test_path(@ordered_test), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ordered_test_path(@ordered_test),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>